### PR TITLE
Add meson

### PR DESCRIPTION
**Pull request by ryonakano**
@aleksandar-stefanovic elementary [announced](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e) that they migrate the build system from CMake to Meson last January and many official apps and third-party apps are updated to use Meson. This PR adds Meson as a new build system of this project.

## Changes Summary

* Add Meson build system
* Update building instruction to use Meson in README.md
* Make metadata files (`.appdata.xml` and `.desktop` files) translatable
* Update translation templates
* Remove no longer necessary CMake related files
* Update Debian packaging to use Meson

This PR is ready for review/merge.

### CODE REVIEW

**Comment by ryonakano** [comment]
@aleksandar-stefanovic I think now the app is ready to publish on elementary OS Juno. It would be great if you would make the app available in AppCenter again.

**Comment by aleksandar-stefanovic** [comment]
@ryonakano yes, I'm planning on doing so. I just need to update the version number in the project to something like 1.3.3, and I'll publish it. Thanks for your contributions!

**Comment by aleksandar-stefanovic** [comment]
@ryonakano I've submitted the release for a review :)

**Comment by ryonakano** [comment]
Nice. Thank you 😊

**Pull request merged**
